---
- name: Deploy Software
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes
    - name: start application in background
      shell: docker-compose up -d
