---
dist: xenial

python:
  - "3.6"

services:
  - docker

script:
  - docker-compose up -d
  - docker-compose run --rm python-app flake8 --exclude venv .
  - docker-compose run --rm python-app python tests/is_table_empty.py