CREATE DATABASE IF NOT EXISTS devopsloft;
USE devopsloft;

CREATE TABLE IF NOT EXISTS users
(id INT(11) AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL,
 username VARCHAR(30),
 password varchar(100),
 signup_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
