version: '2'

services:
  web:
    build:
      context: .
      dockerfile:  docker-files/Dockerfile-app
    ports:
      - "5000:5000"
    depends_on: 
      - "db"

    environment: 
      DB_HOST_NAME : db
      DB_USER_NAME : root
      DB_PASSWORD : 12345
      DB_INSTANCE : devopsloft

  db:
    build:
      context: .
      dockerfile:  docker-files/Dockerfile-mysql
    ports:
      - "3306:3306"
    environment: 
       MYSQL_ROOT_PASSWORD : 12345
