version: "3.7"
services:
  db:
    image: $APP/db
    build: ./db_s2i
    container_name: db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    restart: always

  app:
    image: $APP/app
    build:
      context: ./app_s2i
      args:
        APP_GUEST_PORT: $APP_GUEST_PORT
    container_name: app
    environment:
      - STATCODES
      - ENVIRONMENT
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - APP_GUEST_PORT
      - PYTHONPATH=$$PYTHONPATH:/modules
      - VAULT_ADDR=http://vault:$VAULT_GUEST_PORT
    ports:
      - $APP_HOST_PORT:$APP_GUEST_PORT
    volumes:
      - $BASE_FOLDER/modules:/modules
      - $BASE_FOLDER/.env:/.env
      - $BASE_FOLDER/.env.local:/.env.local
      - $BASE_FOLDER/vault:/vault
    restart: always

  vault:
    image: vault:1.1.2
    container_name: vault
    volumes:
      - $BASE_FOLDER/vault:/vault:rw
    ports:
      - $VAULT_HOST_PORT:$VAULT_GUEST_PORT
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  web:
    image: $APP/web
    build:
      context: ./web_s2i
      args:
        WEB_HOST_PORT: $WEB_HOST_PORT
        WEB_HOST_SECURE_PORT: $WEB_HOST_SECURE_PORT
        APP_HOST_PORT: $APP_HOST_PORT
    container_name: web
    ports:
      - $WEB_HOST_PORT:$WEB_GUEST_PORT
      - $WEB_HOST_SECURE_PORT:$WEB_GUEST_SECURE_PORT
    restart: always
