____ ubuntu:18.04

____ apt-get update -y && \
    apt-get install -y python-pip python-dev

____ ./requirements.txt /app/requirements.txt

____ /app

____ pip install -r requirements.txt

____ . /app

____ [ "python" ]
____ [ "app.py" ]
