# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

        config.vm.define "dev" do |dev|

                dev.vm.box = "ubuntu/bionic64"
                dev.vm.network "forwarded_port", guest: 5000, host: 5000
                dev.vm.network "forwarded_port", guest: 5001, host: 5001
                dev.vm.network "forwarded_port", guest: 9090, host: 9090
                dev.vm.network "forwarded_port", guest: 9100, host: 9100
                dev.vm.network "forwarded_port", guest: 3000, host: 3000
                dev.vm.network "forwarded_port", guest: 8081, host: 8081
                dev.vm.network "forwarded_port", guest: 8080, host: 8080
                dev.vm.provider :virtualbox do |virtualbox,override|
                        virtualbox.name = "devopsloft_dev"
                        virtualbox.memory = 1024
                        virtualbox.cpus = 2
                end
                  config.vm.provision "shell", inline: <<-SCRIPT
                      curl -sL https://get.docker.io/ | sh
                      curl -sL https://raw.githubusercontent.com/dotcloud/docker/master/contrib/completion/bash/docker > /etc/bash_completion.d/docker
                       adduser vagrant docker
                  SCRIPT


        end

        config.vm.define "stage" do |stage|

                stage.vm.synced_folder ".", "/vagrant", disabled: true
                stage.vm.box = "dummy"
                stage.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
                stage.vm.provision "file", source: ".", destination: "$HOME/devopsloft"
                stage.vm.network "forwarded_port", guest: 5000, host: 5000

                stage.vm.provider :aws do |aws,override|
                end

        end

end

eval IO.read("Vagrantfile.local") if File.file?("Vagrantfile.local")
